
module.exports = {
  'ko':{
    // Buttons
    btn_signup: '회원가입',
    btn_login: '로그인',
    btn_logout: '로그아웃',
    btn_confirm: '확인',
    btn_cancel: '취소',
    btn_register: '등록',
    btn_close: '닫기',
    btn_write: '글쓰기',
    btn_modify: '수정',
    btn_delete: '삭제',
    btn_list: '목록',
    btn_more: '더보기',
    btn_refresh: '새로고침',
    btn_prev: '이전',
    btn_next: '다음',
    btn_declare: '신고',
    btn_write_reply: '덧글쓰기',
    btn_attach_emoticon: '이모티콘 첨부',
    btn_attach_img: '이미지 첨부',
    btn_send: '전송',
    btn_realname: '실명 인증',
    btn_reporting: '신고/이의 내역',
    btn_fromlist: '목록으로',
    btn_yes: '예',
    btn_no: '아니오',
    btn_search: '찾기',
    btn_reset: '초기화',

    // SNS 
    kakao: '카카오톡',
    kakaostory: '카카오스토리',
    facebook: '페이스북',
    twitter: '트위터',

    // Icons
    icon_attach: '이미지 첨부',
    icon_new: '새글',
    icon_type_list: '리스트 타입',
    icon_type_card: '카드 타입',
    icon_guide: '안내',

    // Words
    title: '제목',
    notice: '공지',
    share: '공유하기',
    recommend: '추천',
    write: '글쓰기',
    title: '검색',
    hit: '조회',
    comment: '댓글',
    administrator: '관리자',
    level: '레벨',

    // List
    list_msg_delete: '삭제된 게시글 입니다.',
    list_none_article: '등록된 글이 없습니다.',

    // Search form
    search_none: '검색 결과가 없습니다. ',
    search_searchtype_content: '제목+내용',
    search_searchtype_title: '제목',
    search_searchtype_writer: '작성자',
    search_result: '검색결과',
    search_result_count: '건',
    search_result_return: '돌아가기',
    
    // View
    prev_article: '이전글',
    next_article: '다음글',
    more_bookmark: '북마크',
    more_modify: '수정',
    more_delete: '삭제',
    more_report: '신고',
    signature_friend: '친구',
    signature_another_article: '작성글',

    // Comment
    comment_title: '댓글',
    comment_placeholder_logout: '로그인 후 댓글을 입력하실 수 있습니다.',
    comment_placeholder_login: '댓글은 300자까지 작성 가능합니다.',
    comment_list_delete: '삭제된 댓글 입니다.',
    comment_reply_placeholder_logout: '로그인 후 댓글을 입력하실 수 있습니다.',
    comment_reply_placeholder_login: '덧글을 입력하세요.',
    comment_reply_list_delete: '삭제된 덧글 입니다.',

    // Write
    write_placeholder_title: '제목',
    write_placeholder_textarea: '내용을 입력하세요.',
    write_placeholder_contents: '내용을 입력하세요.',
    write_attention: '욕설, 도배, 비방, 루머등 운영정책에 어긋나는 게시물 등록 시에는 글쓰기 제한 등 불이익을 받으실 수 있습니다.',
    
    // editor
    editor_font_face: '글꼴',
    editor_font_size: '크기',
    editor_font_color: '글자색',
    editor_bg_color: '배경색',
    editor_strong: '굵게',
    editor_underline: '밑줄',
    editor_strike: '취소선',
    editor_justify_left: '왼쪽 정렬',
    editor_justify_center: '가운데 정렬',
    editor_justify_right: '오른쪽 정렬',
    editor_link: '링크',
    editor_remove_link: '링크 지우기',
    editor_unordered_list: '글머리 기호',
    editor_ordered_list: '번호 매기기',
    editor_insert_image: '이미지 첨부',
    editor_insert_youtube: '유투브 첨부',
    editor_upload_movie: '동영상',

    // alert
    alert_delete_article: '삭제 하시겠습니까?',
    alert_cancel_article: '글쓰기를 취소하시겠습니까?',
    alert_empty_title: '제목을 입력해 주세요. ',
    alert_too_short_title: '제목은 2자 이상 입력해 주세요.',
    alert_too_long_title: '제목을 50자 이내로 입력해 주세요.  ',
    alert_empty_contents: '내용을 입력하세요.',
    alert_progressing: '요청 중 입니다. 잠시만 기다려 주세요.',
    alert_empty_images: '이미지를 올려주세요.',
    alert_empty_category: '분류를 선택해 주세요.',
    alert_too_short_search_text: '검색어를 2자 이상 입력하세요.',
    alert_too_long_text: '글자를 초과 입력할 수 없습니다.',
    alert_too_short_text: '글자 이상을 입력해 주세요.',
    alert_already_liked: '이미 추천하였습니다',
    alert_delete_comment: '댓글을 삭제하시겠습니까?',
    alert_delete_reply: '덧글을 삭제하시겠습니까?',
    alert_empty_comment: '댓글을 작성해주세요',
    alert_empty_reply: '덧글을 작성해주세요',
    alert_login: '로그인 후 이용하실 수 있습니다.',
    alert_error: '일시적으로 장애가 발생했습니다.',
    alert_comment_login: '로그인 후 댓글을 입력하실 수 있습니다.',
    alert_comment_list_delete: '댓글을 삭제하시겠습니까?',
    alert_comment_reply_login: '로그인 후 덧글을 입력하실 수 있습니다.',
    alert_comment_reply_delete: '덧글을 삭제하시겠습니까?',
    alert_retry: '잠시 후에 다시 이용해 주십시요.',
    alert_realname_check: '본인확인을 하신 후에 게임을 이용하실 수 있습니다.',

    // 신고하기
    report_title: '신고하기',
    report_info: '게시물 신고는 하루에 20회까지 가능합니다.',
    report_remain: '남은 신고 횟수',
    report_number: '회',
    report_reporter: '신고자',
    report_date: '신고일시',
    report_username: '신고 대상자',
    report_reason: '신고 사유',
    report_reason0: '기타',
    report_reason1: '음란성',
    report_reason2: '욕설',
    report_reason3: '일반광고',
    report_reason4: '현금거래',
    report_reason5: '불법프로그램',
    report_reason6: '도배',
    report_reason7: '개인정보',
    report_reason8: '저작권위반',
    report_reason9: '타인비방',
    report_select_reason: '신고 사유를 선택해 주세요.',
    report_error_again: '신고중에 오류가 발생했습니다. 다시 한번 시도해주세요.',
    report_reason: '신고 사유를 선택해 주세요.',
    report_have_done: '신고 처리 되었습니다.'
  },
  'en':{
    // Buttons
    btn_signup: '회원가입',
    btn_login: '로그인',
    btn_logout: '로그아웃',
    btn_confirm: '확인',
    btn_cancel: '취소',
    btn_register: '등록',
    btn_close: '닫기',
    btn_write: '글쓰기',
    btn_modify: '수정',
    btn_delete: '삭제',
    btn_list: '목록',
    btn_more: '더보기',
    btn_refresh: '새로고침',
    btn_prev: '이전',
    btn_next: '다음',
    btn_declare: '신고',
    btn_write_reply: '덧글쓰기',
    btn_attach_emoticon: '이모티콘 첨부',
    btn_attach_img: '이미지 첨부',
    btn_send: '전송',
    btn_realname: '실명 인증',
    btn_reporting: '신고/이의 내역',
    btn_fromlist: '목록으로',
    btn_yes: '예',
    btn_no: '아니오',
    btn_search: '찾기',
    btn_reset: '초기화',

    // SNS 
    kakao: '카카오톡',
    kakaostory: '카카오스토리',
    facebook: '페이스북',
    twitter: '트위터',

    // Icons
    icon_attach: '이미지 첨부',
    icon_new: '새글',
    icon_type_list: '리스트 타입',
    icon_type_card: '카드 타입',
    icon_guide: '안내',

    // Words
    title: '제목',
    notice: '공지',
    share: '공유하기',
    recommend: '추천',
    write: '글쓰기',
    title: '검색',
    hit: '조회',
    comment: '댓글',
    administrator: '관리자',
    level: '레벨',

    // List
    list_msg_delete: '삭제된 게시글 입니다.',
    list_none_article: '등록된 글이 없습니다.',

    // Search form
    search_none: '검색 결과가 없습니다. ',
    search_searchtype_content: '제목+내용',
    search_searchtype_title: '제목',
    search_searchtype_writer: '작성자',
    search_result: '검색결과',
    search_result_count: '건',
    search_result_return: '돌아가기',
    
    // View
    prev_article: '이전글',
    next_article: '다음글',
    more_bookmark: '북마크',
    more_modify: '수정',
    more_delete: '삭제',
    more_report: '신고',
    signature_friend: '친구',
    signature_another_article: '작성글',

    // Comment
    comment_title: '댓글',
    comment_placeholder_logout: '로그인 후 댓글을 입력하실 수 있습니다.',
    comment_placeholder_login: '댓글은 300자까지 작성 가능합니다.',
    comment_list_delete: '삭제된 댓글 입니다.',
    comment_reply_placeholder_logout: '로그인 후 댓글을 입력하실 수 있습니다.',
    comment_reply_placeholder_login: '덧글을 입력하세요.',
    comment_reply_list_delete: '삭제된 덧글 입니다.',

    // Write
    write_placeholder_title: '제목',
    write_placeholder_textarea: '내용을 입력하세요.',
    write_placeholder_contents: '내용을 입력하세요.',
    write_attention: '욕설, 도배, 비방, 루머등 운영정책에 어긋나는 게시물 등록 시에는 글쓰기 제한 등 불이익을 받으실 수 있습니다.',
    
    // editor
    editor_font_face: '글꼴',
    editor_font_size: '크기',
    editor_font_color: '글자색',
    editor_bg_color: '배경색',
    editor_strong: '굵게',
    editor_underline: '밑줄',
    editor_strike: '취소선',
    editor_justify_left: '왼쪽 정렬',
    editor_justify_center: '가운데 정렬',
    editor_justify_right: '오른쪽 정렬',
    editor_link: '링크',
    editor_remove_link: '링크 지우기',
    editor_unordered_list: '글머리 기호',
    editor_ordered_list: '번호 매기기',
    editor_insert_image: '이미지 첨부',
    editor_insert_youtube: '유투브 첨부',
    editor_upload_movie: '동영상',

    // alert
    alert_delete_article: '삭제 하시겠습니까?',
    alert_cancel_article: '글쓰기를 취소하시겠습니까?',
    alert_empty_title: '제목을 입력해 주세요. ',
    alert_too_short_title: '제목은 2자 이상 입력해 주세요.',
    alert_too_long_title: '제목을 50자 이내로 입력해 주세요.  ',
    alert_empty_contents: '내용을 입력하세요.',
    alert_progressing: '요청 중 입니다. 잠시만 기다려 주세요.',
    alert_empty_images: '이미지를 올려주세요.',
    alert_empty_category: '분류를 선택해 주세요.',
    alert_too_short_search_text: '검색어를 2자 이상 입력하세요.',
    alert_too_long_text: '글자를 초과 입력할 수 없습니다.',
    alert_too_short_text: '글자 이상을 입력해 주세요.',
    alert_already_liked: '이미 추천하였습니다',
    alert_delete_comment: '댓글을 삭제하시겠습니까?',
    alert_delete_reply: '덧글을 삭제하시겠습니까?',
    alert_empty_comment: '댓글을 작성해주세요',
    alert_empty_reply: '덧글을 작성해주세요',
    alert_login: '로그인 후 이용하실 수 있습니다.',
    alert_error: '일시적으로 장애가 발생했습니다.',
    alert_comment_login: '로그인 후 댓글을 입력하실 수 있습니다.',
    alert_comment_list_delete: '댓글을 삭제하시겠습니까?',
    alert_comment_reply_login: '로그인 후 덧글을 입력하실 수 있습니다.',
    alert_comment_reply_delete: '덧글을 삭제하시겠습니까?',
    alert_retry: '잠시 후에 다시 이용해 주십시요.',
    alert_realname_check: '본인확인을 하신 후에 게임을 이용하실 수 있습니다.',

    // 신고하기
    report_title: '신고하기',
    report_info: '게시물 신고는 하루에 20회까지 가능합니다.',
    report_remain: '남은 신고 횟수',
    report_number: '회',
    report_reporter: '신고자',
    report_date: '신고일시',
    report_username: '신고 대상자',
    report_reason: '신고 사유',
    report_reason0: '기타',
    report_reason1: '음란성',
    report_reason2: '욕설',
    report_reason3: '일반광고',
    report_reason4: '현금거래',
    report_reason5: '불법프로그램',
    report_reason6: '도배',
    report_reason7: '개인정보',
    report_reason8: '저작권위반',
    report_reason9: '타인비방',
    report_select_reason: '신고 사유를 선택해 주세요.',
    report_error_again: '신고중에 오류가 발생했습니다. 다시 한번 시도해주세요.',
    report_reason: '신고 사유를 선택해 주세요.',
    report_have_done: '신고 처리 되었습니다.'
  },
  'ja':{
    // Buttons
    btn_signup: '회원가입',
    btn_login: '로그인',
    btn_logout: '로그아웃',
    btn_confirm: '확인',
    btn_cancel: '취소',
    btn_register: '등록',
    btn_close: '닫기',
    btn_write: '글쓰기',
    btn_modify: '수정',
    btn_delete: '삭제',
    btn_list: '목록',
    btn_more: '더보기',
    btn_refresh: '새로고침',
    btn_prev: '이전',
    btn_next: '다음',
    btn_declare: '신고',
    btn_write_reply: '덧글쓰기',
    btn_attach_emoticon: '이모티콘 첨부',
    btn_attach_img: '이미지 첨부',
    btn_send: '전송',
    btn_realname: '실명 인증',
    btn_reporting: '신고/이의 내역',
    btn_fromlist: '목록으로',
    btn_yes: '예',
    btn_no: '아니오',
    btn_search: '찾기',
    btn_reset: '초기화',

    // SNS 
    kakao: '카카오톡',
    kakaostory: '카카오스토리',
    facebook: '페이스북',
    twitter: '트위터',

    // Icons
    icon_attach: '이미지 첨부',
    icon_new: '새글',
    icon_type_list: '리스트 타입',
    icon_type_card: '카드 타입',
    icon_guide: '안내',

    // Words
    title: '제목',
    notice: '공지',
    share: '공유하기',
    recommend: '추천',
    write: '글쓰기',
    title: '검색',
    hit: '조회',
    comment: '댓글',
    administrator: '관리자',
    level: '레벨',

    // List
    list_msg_delete: '삭제된 게시글 입니다.',
    list_none_article: '등록된 글이 없습니다.',

    // Search form
    search_none: '검색 결과가 없습니다. ',
    search_searchtype_content: '제목+내용',
    search_searchtype_title: '제목',
    search_searchtype_writer: '작성자',
    search_result: '검색결과',
    search_result_count: '건',
    search_result_return: '돌아가기',
    
    // View
    prev_article: '이전글',
    next_article: '다음글',
    more_bookmark: '북마크',
    more_modify: '수정',
    more_delete: '삭제',
    more_report: '신고',
    signature_friend: '친구',
    signature_another_article: '작성글',

    // Comment
    comment_title: '댓글',
    comment_placeholder_logout: '로그인 후 댓글을 입력하실 수 있습니다.',
    comment_placeholder_login: '댓글은 300자까지 작성 가능합니다.',
    comment_list_delete: '삭제된 댓글 입니다.',
    comment_reply_placeholder_logout: '로그인 후 댓글을 입력하실 수 있습니다.',
    comment_reply_placeholder_login: '덧글을 입력하세요.',
    comment_reply_list_delete: '삭제된 덧글 입니다.',

    // Write
    write_placeholder_title: '제목',
    write_placeholder_textarea: '내용을 입력하세요.',
    write_placeholder_contents: '내용을 입력하세요.',
    write_attention: '욕설, 도배, 비방, 루머등 운영정책에 어긋나는 게시물 등록 시에는 글쓰기 제한 등 불이익을 받으실 수 있습니다.',
    
    // editor
    editor_font_face: '글꼴',
    editor_font_size: '크기',
    editor_font_color: '글자색',
    editor_bg_color: '배경색',
    editor_strong: '굵게',
    editor_underline: '밑줄',
    editor_strike: '취소선',
    editor_justify_left: '왼쪽 정렬',
    editor_justify_center: '가운데 정렬',
    editor_justify_right: '오른쪽 정렬',
    editor_link: '링크',
    editor_remove_link: '링크 지우기',
    editor_unordered_list: '글머리 기호',
    editor_ordered_list: '번호 매기기',
    editor_insert_image: '이미지 첨부',
    editor_insert_youtube: '유투브 첨부',
    editor_upload_movie: '동영상',

    // alert
    alert_delete_article: '삭제 하시겠습니까?',
    alert_cancel_article: '글쓰기를 취소하시겠습니까?',
    alert_empty_title: '제목을 입력해 주세요. ',
    alert_too_short_title: '제목은 2자 이상 입력해 주세요.',
    alert_too_long_title: '제목을 50자 이내로 입력해 주세요.  ',
    alert_empty_contents: '내용을 입력하세요.',
    alert_progressing: '요청 중 입니다. 잠시만 기다려 주세요.',
    alert_empty_images: '이미지를 올려주세요.',
    alert_empty_category: '분류를 선택해 주세요.',
    alert_too_short_search_text: '검색어를 2자 이상 입력하세요.',
    alert_too_long_text: '글자를 초과 입력할 수 없습니다.',
    alert_too_short_text: '글자 이상을 입력해 주세요.',
    alert_already_liked: '이미 추천하였습니다',
    alert_delete_comment: '댓글을 삭제하시겠습니까?',
    alert_delete_reply: '덧글을 삭제하시겠습니까?',
    alert_empty_comment: '댓글을 작성해주세요',
    alert_empty_reply: '덧글을 작성해주세요',
    alert_login: '로그인 후 이용하실 수 있습니다.',
    alert_error: '일시적으로 장애가 발생했습니다.',
    alert_comment_login: '로그인 후 댓글을 입력하실 수 있습니다.',
    alert_comment_list_delete: '댓글을 삭제하시겠습니까?',
    alert_comment_reply_login: '로그인 후 덧글을 입력하실 수 있습니다.',
    alert_comment_reply_delete: '덧글을 삭제하시겠습니까?',
    alert_retry: '잠시 후에 다시 이용해 주십시요.',
    alert_realname_check: '본인확인을 하신 후에 게임을 이용하실 수 있습니다.',

    // 신고하기
    report_title: '신고하기',
    report_info: '게시물 신고는 하루에 20회까지 가능합니다.',
    report_remain: '남은 신고 횟수',
    report_number: '회',
    report_reporter: '신고자',
    report_date: '신고일시',
    report_username: '신고 대상자',
    report_reason: '신고 사유',
    report_reason0: '기타',
    report_reason1: '음란성',
    report_reason2: '욕설',
    report_reason3: '일반광고',
    report_reason4: '현금거래',
    report_reason5: '불법프로그램',
    report_reason6: '도배',
    report_reason7: '개인정보',
    report_reason8: '저작권위반',
    report_reason9: '타인비방',
    report_select_reason: '신고 사유를 선택해 주세요.',
    report_error_again: '신고중에 오류가 발생했습니다. 다시 한번 시도해주세요.',
    report_reason: '신고 사유를 선택해 주세요.',
    report_have_done: '신고 처리 되었습니다.'
  },
  'zh-tw':{
    // Buttons
    btn_signup: '회원가입',
    btn_login: '로그인',
    btn_logout: '로그아웃',
    btn_confirm: '확인',
    btn_cancel: '취소',
    btn_register: '등록',
    btn_close: '닫기',
    btn_write: '글쓰기',
    btn_modify: '수정',
    btn_delete: '삭제',
    btn_list: '목록',
    btn_more: '더보기',
    btn_refresh: '새로고침',
    btn_prev: '이전',
    btn_next: '다음',
    btn_declare: '신고',
    btn_write_reply: '덧글쓰기',
    btn_attach_emoticon: '이모티콘 첨부',
    btn_attach_img: '이미지 첨부',
    btn_send: '전송',
    btn_realname: '실명 인증',
    btn_reporting: '신고/이의 내역',
    btn_fromlist: '목록으로',
    btn_yes: '예',
    btn_no: '아니오',
    btn_search: '찾기',
    btn_reset: '초기화',

    // SNS 
    kakao: '카카오톡',
    kakaostory: '카카오스토리',
    facebook: '페이스북',
    twitter: '트위터',

    // Icons
    icon_attach: '이미지 첨부',
    icon_new: '새글',
    icon_type_list: '리스트 타입',
    icon_type_card: '카드 타입',
    icon_guide: '안내',

    // Words
    title: '제목',
    notice: '공지',
    share: '공유하기',
    recommend: '추천',
    write: '글쓰기',
    title: '검색',
    hit: '조회',
    comment: '댓글',
    administrator: '관리자',
    level: '레벨',

    // List
    list_msg_delete: '삭제된 게시글 입니다.',
    list_none_article: '등록된 글이 없습니다.',

    // Search form
    search_none: '검색 결과가 없습니다. ',
    search_searchtype_content: '제목+내용',
    search_searchtype_title: '제목',
    search_searchtype_writer: '작성자',
    search_result: '검색결과',
    search_result_count: '건',
    search_result_return: '돌아가기',
    
    // View
    prev_article: '이전글',
    next_article: '다음글',
    more_bookmark: '북마크',
    more_modify: '수정',
    more_delete: '삭제',
    more_report: '신고',
    signature_friend: '친구',
    signature_another_article: '작성글',

    // Comment
    comment_title: '댓글',
    comment_placeholder_logout: '로그인 후 댓글을 입력하실 수 있습니다.',
    comment_placeholder_login: '댓글은 300자까지 작성 가능합니다.',
    comment_list_delete: '삭제된 댓글 입니다.',
    comment_reply_placeholder_logout: '로그인 후 댓글을 입력하실 수 있습니다.',
    comment_reply_placeholder_login: '덧글을 입력하세요.',
    comment_reply_list_delete: '삭제된 덧글 입니다.',

    // Write
    write_placeholder_title: '제목',
    write_placeholder_textarea: '내용을 입력하세요.',
    write_placeholder_contents: '내용을 입력하세요.',
    write_attention: '욕설, 도배, 비방, 루머등 운영정책에 어긋나는 게시물 등록 시에는 글쓰기 제한 등 불이익을 받으실 수 있습니다.',
    
    // editor
    editor_font_face: '글꼴',
    editor_font_size: '크기',
    editor_font_color: '글자색',
    editor_bg_color: '배경색',
    editor_strong: '굵게',
    editor_underline: '밑줄',
    editor_strike: '취소선',
    editor_justify_left: '왼쪽 정렬',
    editor_justify_center: '가운데 정렬',
    editor_justify_right: '오른쪽 정렬',
    editor_link: '링크',
    editor_remove_link: '링크 지우기',
    editor_unordered_list: '글머리 기호',
    editor_ordered_list: '번호 매기기',
    editor_insert_image: '이미지 첨부',
    editor_insert_youtube: '유투브 첨부',
    editor_upload_movie: '동영상',

    // alert
    alert_delete_article: '삭제 하시겠습니까?',
    alert_cancel_article: '글쓰기를 취소하시겠습니까?',
    alert_empty_title: '제목을 입력해 주세요. ',
    alert_too_short_title: '제목은 2자 이상 입력해 주세요.',
    alert_too_long_title: '제목을 50자 이내로 입력해 주세요.  ',
    alert_empty_contents: '내용을 입력하세요.',
    alert_progressing: '요청 중 입니다. 잠시만 기다려 주세요.',
    alert_empty_images: '이미지를 올려주세요.',
    alert_empty_category: '분류를 선택해 주세요.',
    alert_too_short_search_text: '검색어를 2자 이상 입력하세요.',
    alert_too_long_text: '글자를 초과 입력할 수 없습니다.',
    alert_too_short_text: '글자 이상을 입력해 주세요.',
    alert_already_liked: '이미 추천하였습니다',
    alert_delete_comment: '댓글을 삭제하시겠습니까?',
    alert_delete_reply: '덧글을 삭제하시겠습니까?',
    alert_empty_comment: '댓글을 작성해주세요',
    alert_empty_reply: '덧글을 작성해주세요',
    alert_login: '로그인 후 이용하실 수 있습니다.',
    alert_error: '일시적으로 장애가 발생했습니다.',
    alert_comment_login: '로그인 후 댓글을 입력하실 수 있습니다.',
    alert_comment_list_delete: '댓글을 삭제하시겠습니까?',
    alert_comment_reply_login: '로그인 후 덧글을 입력하실 수 있습니다.',
    alert_comment_reply_delete: '덧글을 삭제하시겠습니까?',
    alert_retry: '잠시 후에 다시 이용해 주십시요.',
    alert_realname_check: '본인확인을 하신 후에 게임을 이용하실 수 있습니다.',

    // 신고하기
    report_title: '신고하기',
    report_info: '게시물 신고는 하루에 20회까지 가능합니다.',
    report_remain: '남은 신고 횟수',
    report_number: '회',
    report_reporter: '신고자',
    report_date: '신고일시',
    report_username: '신고 대상자',
    report_reason: '신고 사유',
    report_reason0: '기타',
    report_reason1: '음란성',
    report_reason2: '욕설',
    report_reason3: '일반광고',
    report_reason4: '현금거래',
    report_reason5: '불법프로그램',
    report_reason6: '도배',
    report_reason7: '개인정보',
    report_reason8: '저작권위반',
    report_reason9: '타인비방',
    report_select_reason: '신고 사유를 선택해 주세요.',
    report_error_again: '신고중에 오류가 발생했습니다. 다시 한번 시도해주세요.',
    report_reason: '신고 사유를 선택해 주세요.',
    report_have_done: '신고 처리 되었습니다.'
  }
}
