
module.exports = {
  'ko':{
    alert_valid_title: '제목을 입력하세요.',
    alert_valid_contents: '내용을 입력하세요.',
    alert_valid_category: '카테고리를 선택해주세요.',
    alert_valid_board: '게시판을 선택해주세요.',
    alert_valid_image_maximum: '게시글 당 이미지는 최대 10장까지 등록할 수 있습니다.', // 이미지가 10장 이상 등록되었을 때
    alert_valid_video_url: '영상 URL(코드)를 다시 확인해 주세요',
    alert_valid_upload: '현재 진행 중인 작업이 있습니다.\n잠시만 기다려 주세요.',
    alert_valid_upload_complete: '영상 업로드가 완료되었습니다.',
    alert_load_template: '임시저장글을 불러오시겠습니까?\n(작성하던 글은 유지되지 않습니다.)',
    alert_login: '로그인 후 이용하실 수 있습니다.',
    confirm_leave: '이 페이지에서 벗어나시겠습니까?',
    confirm_write_cancel: '글 작성을 취소하시겠습니까?',
    error_auth: '접근 권한이 없는 페이지 입니다.',
    error_selfauth: '본인 확인이 필요합니다.',
    error_punish: '제재된 계정입니다. 자세한 사항은 고객센터로 문의 바랍니다.',
    error_level: '레벨 이상의 캐릭터를 선택하셔야 합니다.',
    btn_apply: '등록',
    btn_cancel: '취소',
    btn_close: '닫기',
    btn_delete: '삭제',
    btn_remove: '제거',
    layer_video_title: '영상첨부',
    layer_video_copy1: '공유하려는 YouTube 영상의 코드, 주소, iframe 태그 등을 입력하면 영상을 삽입할 수 있습니다.', // 지원플랫폼: youtube
    layer_video_copy2: '공유하려는 YouTube, Twitch TV 영상의 코드, 주소,iframe 태그 등을 입력하면 영상을 삽입할 수 있습니다.', // 지원플랫폼: youtube, twitch
    layer_video_copy3: '공유하려는 YouTube, Twitch TV, Afreeca TV 영상의 코드, 주소, iframe 태그 등을 입력하면 영상을 삽입할 수 있습니다. ', // 지원플랫폼: youtube, twitch, afreecaTV

    error_file_server: '파일 서버 에러입니다. 서비스 이용에 불편을 드려 죄송합니다.',
    error_exceed_max_upload: '허용 업로드 용량을 초과하였습니다.서비스 이용에 불편을 드려 죄송합니다',
    error_exceed_file_size: '한 파일당 최대 10MB까지 등록 할 수 있습니다',
    error_exceed_file_size_3m: '한 파일당 최대 3MB까지 등록 할 수 있습니다.',
    error_invalid_request: '서비스 이용에 불편을 드려 죄송합니다.',
    error_invalid_channel: '서비스 이용에 불편을 드려 죄송합니다.',
    error_invalid_type: 'JPG, JPEG, PNG, BMP 형식만 등록할 수 있습니다. 사진의 주소(URL)가 잘못 입력 되었거나 지원되지 않는 형식일 수 있으니 확인 후 다시 등록해 주시기 바랍니다.',
    error_invalid_token: '오류가 발생해서 페이지를 \'새로 고침(F5)\' 해야 합니다. 작성하셨던 소중한 글이 모두 지워지게 되므로, 다른 곳에 저장 후 \'새로 고침\' 해주시기 바랍니다.',
    error_expired_token: '오류가 발생해서 페이지를 \'새로 고침(F5)\' 해야 합니다. 작성하셨던 소중한 글이 모두 지워지게 되므로, 다른 곳에 저장 후 \'새로 고침\' 해주시기 바랍니다.',
    error_exceed_file: '한 번에 등록할 수 있는 파일 개수가 초과되었습니다. 불필요한 사진은 삭제 후 다시 등록해 주시기 바랍니다.',
    error_auth_fail: '로그아웃 되었거나 권한이 없습니다.'
  },
  'en':{
    alert_valid_title: 'Please enter a title.',
    alert_valid_contents: 'Write something here.',
    alert_valid_category: 'Please select a category.',
    alert_valid_board: 'Please select a discussion board.',
    alert_valid_image_maximum: 'You can upload up to 10 images per post.', //Upon attempt to upload over 10 images.
    alert_valid_video_url: 'Please check the video URL (code) again.',
    alert_valid_upload: 'Task in progress...\nPlease wait a moment.',
    alert_valid_upload_complete: 'The Video has been uploaded successfully.',
    alert_load_template: 'Open a saved draft?\n(Changes will not be saved.)',
    alert_login: 'Please log in to continue.',
    confirm_leave: 'Leave the current page?',
    confirm_write_cancel: 'Quit without saving?',
    error_auth: 'You do not have access to this page.',
    error_selfauth: 'ID verification is required.',
    error_punish: 'Your account has been restricted. Please contact Customer Service for further assistance.',
    error_level: 'Please select a character with level 10 or higher.',
    btn_apply: 'Register',
    btn_cancel: 'Cancel',
    btn_close: 'Close',
    btn_delete: 'Delete',
    btn_remove: 'Remove',
    layer_video_title: 'Attached Video',
    layer_video_copy1: 'Enter code, address and iframe tag info of the YouTube video to share.', //Supported platform: YouTube
    layer_video_copy2: 'Enter code, address and iframe tag info of the YouTube or Twitch TV video to share.', //Supported platform: YouTube, Twitch
    layer_video_copy3: 'Enter code, address and iframe tag info of the YouTube, Twitch TV or Afreeca TV video to share.', //Supported platform: YouTube, Twitch, Afreeca TV

    error_file_server: 'File server error. We apologize for the inconvenience.',
    error_exceed_max_upload: 'Exceeded the maximum upload size. We apologize for the inconvenience.',
    error_exceed_file_size: 'The file must be 10MB or less in size.',
    error_exceed_file_size_3m: 'The file must be 3MB or less in size.',
    error_invalid_request: 'We apologize for the inconvenience.',
    error_invalid_channel: 'We apologize for the inconvenience.',
    error_invalid_type: 'Only JPG, JPEG, PNG and BMP formats are supported. Please check if the URL and image format is valid.',
    error_invalid_token: 'An error has occurred and you need to \'refresh (F5)\' this page. Please save your posting separately before you \'refresh\' this page.',
    error_expired_token: 'An error has occurred and you need to \'refresh (F5)\' this page. Please save your posting separately before you \'refresh\' this page.',
    error_exceed_file: 'Exceeded maximum number of image files that can be registered at once. Delete all unnecessary images and register again.',
    error_auth_fail: 'You are either logged out or have no authorization.'
  },
  'ja':{
    alert_valid_title: '제목을 입력하세요.',
    alert_valid_contents: '내용을 입력하세요.',
    alert_valid_category: '카테고리를 선택해주세요.',
    alert_valid_board: '게시판을 선택해주세요.',
    alert_valid_image_maximum: '게시글 당 이미지는 최대 10장까지 등록할 수 있습니다.', // 이미지가 10장 이상 등록되었을 때
    alert_valid_video_url: '영상 URL(코드)를 다시 확인해 주세요',
    alert_valid_upload: '현재 진행 중인 작업이 있습니다.\n잠시만 기다려 주세요.',
    alert_valid_upload_complete: '영상 업로드가 완료되었습니다.',
    alert_load_template: '임시저장글을 불러오시겠습니까?\n(작성하던 글은 유지되지 않습니다.)',
    alert_login: '로그인 후 이용하실 수 있습니다.',
    confirm_leave: '이 페이지에서 벗어나시겠습니까?',
    confirm_write_cancel: '글 작성을 취소하시겠습니까?',
    error_auth: '접근 권한이 없는 페이지 입니다.',
    error_selfauth: '본인 확인이 필요합니다.',
    error_punish: '제재된 계정입니다. 자세한 사항은 고객센터로 문의 바랍니다.',
    error_level: '레벨 이상의 캐릭터를 선택하셔야 합니다.',
    btn_apply: '등록',
    btn_cancel: '취소',
    btn_close: '닫기',
    btn_delete: '삭제',
    btn_remove: '제거',
    layer_video_title: '영상첨부',
    layer_video_copy1: '공유하려는 YouTube 영상의 코드, 주소, iframe 태그 등을 입력하면 영상을 삽입할 수 있습니다.', // 지원플랫폼: youtube
    layer_video_copy2: '공유하려는 YouTube, Twitch TV 영상의 코드, 주소,iframe 태그 등을 입력하면 영상을 삽입할 수 있습니다.', // 지원플랫폼: youtube, twitch
    layer_video_copy3: '공유하려는 YouTube, Twitch TV, Afreeca TV 영상의 코드, 주소, iframe 태그 등을 입력하면 영상을 삽입할 수 있습니다. ', // 지원플랫폼: youtube, twitch, afreecaTV

    error_file_server: '파일 서버 에러입니다. 서비스 이용에 불편을 드려 죄송합니다.',
    error_exceed_max_upload: '허용 업로드 용량을 초과하였습니다.서비스 이용에 불편을 드려 죄송합니다',
    error_exceed_file_size: '한 파일당 최대 10MB까지 등록 할 수 있습니다',
    error_exceed_file_size_3m: '한 파일당 최대 3MB까지 등록 할 수 있습니다.',
    error_invalid_request: '서비스 이용에 불편을 드려 죄송합니다.',
    error_invalid_channel: '서비스 이용에 불편을 드려 죄송합니다.',
    error_invalid_type: 'JPG, JPEG, PNG, BMP 형식만 등록할 수 있습니다. 사진의 주소(URL)가 잘못 입력 되었거나 지원되지 않는 형식일 수 있으니 확인 후 다시 등록해 주시기 바랍니다.',
    error_invalid_token: '오류가 발생해서 페이지를 \'새로 고침(F5)\' 해야 합니다. 작성하셨던 소중한 글이 모두 지워지게 되므로, 다른 곳에 저장 후 \'새로 고침\' 해주시기 바랍니다.',
    error_expired_token: '오류가 발생해서 페이지를 \'새로 고침(F5)\' 해야 합니다. 작성하셨던 소중한 글이 모두 지워지게 되므로, 다른 곳에 저장 후 \'새로 고침\' 해주시기 바랍니다.',
    error_exceed_file: '한 번에 등록할 수 있는 파일 개수가 초과되었습니다. 불필요한 사진은 삭제 후 다시 등록해 주시기 바랍니다.',
    error_auth_fail: '로그아웃 되었거나 권한이 없습니다.'
  },
  'zh':{
    alert_valid_title: '請輸入標題。',
    alert_valid_contents: '請輸入內容。',
    alert_valid_category: '請選擇類別。',
    alert_valid_board: '請選擇留言版。',
    alert_valid_image_maximum: '每篇文章最多只能上傳10張圖片。', //上傳超過10張圖片時
    alert_valid_video_url: '請再次確認影片URL（編碼）',
    alert_valid_upload: '目前有作業進行中。\n請稍等。',
    alert_valid_upload_complete: '影片上傳完成。',
    alert_load_template: '是否要開啟暫存文章？\n（不會保留原撰寫文章。）',
    alert_login: '登入後即可使用',
    confirm_leave: '確定離開此頁面嗎',
    confirm_write_cancel: '確定取消撰寫文章嗎',
    error_auth: '沒有權限存取該頁面。',
    error_selfauth: '需進行本人認證。',
    error_punish: '該帳號被制裁。詳細內容請洽客服中心。',
    error_level: '必須選擇等級以上的角色。',
    btn_apply: '登錄',
    btn_cancel: '取消',
    btn_close: '關閉',
    btn_delete: '刪除',
    btn_remove: '移除',
    layer_video_title: '附件影片',
    layer_video_copy1: '輸入欲分享的YouTube影片編碼、網址、iframe標籤等即可插入影片。',
    layer_video_copy2: '輸入欲分享的YouTube、Twitch TV影片編碼、網址、iframe標籤等即可插入影片。',
    layer_video_copy3: '輸入欲分享的YouTube、Twitch TV、Afreeca TV影片編碼、網址、iframe標籤等即可插入影片。',

    error_file_server: '檔案伺服器錯誤。很抱歉造成服務使用上的不便。',
    error_exceed_max_upload: '超過可上傳的容量大小。很抱歉造成服務使用上的不便。',
    error_exceed_file_size: '每個檔案最大上傳限制為10MB',
    error_exceed_file_size_3m: '每個檔案最大上傳限制為3MB。',
    error_invalid_request: '很抱歉造成服務使用上的不便。',
    error_invalid_channel: '很抱歉造成服務使用上的不便。',
    error_invalid_type: '只能上傳JPG、JPEG、PNG、BMP格式。照片的網址（URL）輸入錯誤或有不支援的格式，請確認後再次上傳。',
    error_invalid_token: '出現錯誤需要\'重新整理（F5）頁面\'。您輸入的文章將會被清除，請另外儲存後\'重新整理\'頁面。',
    error_expired_token: '出現錯誤需要\'重新整理（F5）頁面\'。您輸入的文章將會被清除，請另外儲存後\'重新整理\'頁面。',
    error_exceed_file: '超過一次可上傳的檔案數量。請刪除不需要的照片後再次上傳。',
    error_auth_fail: '已登出或沒有權限。'
  }
}
